<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 17-7-4
 * Time: 上午10:42
 */

namespace backend\modules\user\models;


class UserAuthCode extends \common\models\UserAuthCode
{
    public function rules()
    {
        return [
            [['bind_user', 'bind_at', 'created_by', 'created_at', 'updated_by', 'updated_at', 'status'], 'integer'],
            [['code'], 'string', 'max' => 50],
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert){
            $this->code = \Yii::$app->security->generateRandomString(40).NOW_TIME;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}