<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 17-7-4
 * Time: 下午5:21
 */

namespace frontend\components\behaviors;


use yii\filters\AccessControl;

class Check extends AccessControl
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}